version: '3'
services:
  db:
    image: mysql
    restart: always
    env_file:
      - env
    volumes:
      - db-data:/var/lib/mysql
  magento:
    image: alexcheng/magento2
    volumes:
      - magento_data:/var/www/html
    ports:
      - "80:80"
      - "50000:50000"
    links:
      - db
    env_file:
      - env
volumes:
  db-data:
